tagFormat: ${version}
branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/exec"
    - prepareCmd: >
        echo "${nextRelease.version}" > .version
  - - "@semantic-release/git"
    - message: "ci(release): ${nextRelease.version}"
      assets:
        - .version
        - CHANGELOG.md
