name: ci-pull-request

on:
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: docker-setup
        name: docker-setup
        run: |
          docker buildx create \
          --use \
          --platform linux/amd64,linux/arm64
      - id: docker-build
        name: docker-build
        run: |
          docker buildx build . \
          --platform=linux/amd64,linux/arm64
