name: release

on:
  workflow_dispatch:
    branches: [ main ]

defaults:
  run:
    shell: bash

env:
  GIT_AUTHOR_NAME: ${{ github.actor }}
  GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
  GIT_COMMITTER_NAME: ${{ github.actor }}
  GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: setup-node
        name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - id: release
        name: release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          npm install
          npm run release
